/** Configuration du design system "Pubwek Sovereign FinTech". */
module.exports = {
  darkMode: "class",
  // Le JS partage fabrique des elements a la volee (apercus d'images,
  // boutons de position) : ses classes doivent etre scannees elles aussi,
  // sinon elles seraient absentes du CSS genere.
  content: ["./templates/**/*.html", "./static/js/**/*.js"],
  theme: {
    extend: {
      colors: {
        "success-light": "#ECFDF5",
        "success": "#047857",
        "success-deep": "#064E3B",
        "canvas-cream": "#F8FAFC",
        "primary-container": "#066FA7",
        "tertiary-container": "#0070A3",
        "primary-fixed-dim": "#95CFE0",
        "tertiary-fixed": "#ABECFD",
        "surface-container-highest": "#dae2fd",
        "brand-light": "#F0FBFD",
        "secondary": "#904d00",
        "outline-variant": "#BCC8C8",
        "surface-bright": "#faf8ff",
        "on-primary-fixed-variant": "#004B73",
        "inverse-surface": "#283044",
        "amber-rich": "#D97706",
        "slate-night": "#090D16",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb77d",
        "surface-container": "#eaedff",
        "secondary-fixed": "#ffdcc3",
        "surface-container-low": "#f2f3ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001F28",
        "surface-tint": "#00649A",
        "error": "#ba1a1a",
        "on-primary-container": "#C2F2FE",
        "on-error-container": "#93000a",
        "primary-fixed": "#B7EBF8",
        "on-secondary-fixed": "#2f1500",
        "on-primary-fixed": "#001F2A",
        "celtiis-green": "#00A859",
        "inverse-primary": "#95CFE0",
        "on-tertiary": "#ffffff",
        "brand-primary": "#066FA7",
        "brand-deep": "#08486E",
        "on-secondary-fixed-variant": "#6e3900",
        "slate-midnight": "#0F172A",
        "amber-soft": "#FEF3C7",
        "on-surface": "#131b2e",
        "on-background": "#131b2e",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#B4F4FF",
        "slate-border": "#E2E8F0",
        "secondary-container": "#fe932c",
        "on-tertiary-fixed-variant": "#004D6C",
        "surface-variant": "#dae2fd",
        "background": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#faf8ff",
        "inverse-on-surface": "#eef0ff",
        "tertiary": "#00567C",
        "on-secondary-container": "#663500",
        "surface-container-high": "#e2e7ff",
        "on-surface-variant": "#3E4849",
        "amber-vibrant": "#F59E0B",
        "outline": "#6E797A",
        "moov-blue": "#005BAA",
        "primary": "#005682",
        "brand-bright": "#1EADEC",
        "surface-dim": "#d2d9f4",
        "tertiary-fixed-dim": "#83D1E8",
        "momo-yellow": "#FFCC00"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin": "1.75rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-xl": "1.75rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem",
        "space-2xs": "0.25rem",
        "space-3xl": "3.5rem",
        "space-2xl": "2.5rem",
        "gutter": "1.25rem",
        "space-lg": "1.375rem",
        "space-xs": "0.5rem"
      },
      fontFamily: {
        "label-numeric-lg": ["JetBrains Mono", "Mono Secours", "ui-monospace", "monospace"],
        "display-hero-mobile": ["Plus Jakarta Sans", "Jakarta Secours", "system-ui", "sans-serif"],
        "body-xl": ["Inter", "Inter Secours", "system-ui", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "Jakarta Secours", "system-ui", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "Jakarta Secours", "system-ui", "sans-serif"],
        "label-numeric-md": ["JetBrains Mono", "Mono Secours", "ui-monospace", "monospace"],
        "display-hero": ["Plus Jakarta Sans", "Jakarta Secours", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "Inter Secours", "system-ui", "sans-serif"],
        "body-md": ["Inter", "Inter Secours", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "Inter Secours", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "Jakarta Secours", "system-ui", "sans-serif"],
        "caption": ["Inter", "Inter Secours", "system-ui", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "Jakarta Secours", "system-ui", "sans-serif"]
      },
      fontSize: {
        "label-numeric-lg": ["27px", { lineHeight: "31px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-xl": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["17px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "27px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-numeric-md": ["17px", { lineHeight: "23px", fontWeight: "600" }],
        "display-hero": ["42px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "15px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "31px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "35px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  }
};
