/** Configuration du design system "Pubwek Sovereign FinTech". */
module.exports = {
  darkMode: "class",
  // Le JS partage fabrique des elements a la volee (apercus d'images,
  // boutons de position) : ses classes doivent etre scannees elles aussi,
  // sinon elles seraient absentes du CSS genere.
  content: ["./templates/**/*.html", "./static/js/**/*.js"],
  theme: {
    extend: {
      colors: {
        "canvas-cream": "#F8FAFC",
        "primary-container": "#047857",
        "tertiary-container": "#007852",
        "primary-fixed-dim": "#7bd8b1",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#dae2fd",
        "emerald-light": "#ECFDF5",
        "secondary": "#904d00",
        "outline-variant": "#bdc9c1",
        "surface-bright": "#faf8ff",
        "on-primary-fixed-variant": "#00513a",
        "inverse-surface": "#283044",
        "amber-rich": "#D97706",
        "slate-night": "#090D16",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb77d",
        "surface-container": "#eaedff",
        "secondary-fixed": "#ffdcc3",
        "surface-container-low": "#f2f3ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "surface-tint": "#006c4e",
        "error": "#ba1a1a",
        "on-primary-container": "#9ffdd3",
        "on-error-container": "#93000a",
        "primary-fixed": "#97f5cc",
        "on-secondary-fixed": "#2f1500",
        "on-primary-fixed": "#002115",
        "celtiis-green": "#00A859",
        "inverse-primary": "#7bd8b1",
        "on-tertiary": "#ffffff",
        "emerald-primary": "#047857",
        "emerald-deep": "#064E3B",
        "on-secondary-fixed-variant": "#6e3900",
        "slate-midnight": "#0F172A",
        "amber-soft": "#FEF3C7",
        "on-surface": "#131b2e",
        "on-background": "#131b2e",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#8fffc9",
        "slate-border": "#E2E8F0",
        "secondary-container": "#fe932c",
        "on-tertiary-fixed-variant": "#005236",
        "surface-variant": "#dae2fd",
        "background": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#faf8ff",
        "inverse-on-surface": "#eef0ff",
        "tertiary": "#005d3e",
        "on-secondary-container": "#663500",
        "surface-container-high": "#e2e7ff",
        "on-surface-variant": "#3e4943",
        "amber-vibrant": "#F59E0B",
        "outline": "#6e7a73",
        "moov-blue": "#005BAA",
        "primary": "#005d42",
        "emerald-bright": "#10B981",
        "surface-dim": "#d2d9f4",
        "tertiary-fixed-dim": "#4edea3",
        "momo-yellow": "#FFCC00"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin": "1.75rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-xl": "1.75rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem",
        "space-2xs": "0.25rem",
        "space-3xl": "3.5rem",
        "space-2xl": "2.5rem",
        "gutter": "1.25rem",
        "space-lg": "1.375rem",
        "space-xs": "0.5rem"
      },
      fontFamily: {
        "label-numeric-lg": ["JetBrains Mono"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-xl": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-numeric-md": ["JetBrains Mono"],
        "display-hero": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "caption": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-numeric-lg": ["27px", { lineHeight: "31px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-xl": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["17px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "27px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-numeric-md": ["17px", { lineHeight: "23px", fontWeight: "600" }],
        "display-hero": ["42px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "15px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "31px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "35px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  }
};
